name: x86 GCC

on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    name: Release Tests
    runs-on: ubuntu-24.04

    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-13 g++-13

      - name: Cache build dependencies
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.cmake_deps
          key: cmake-deps-ubuntu-24.04-gcc-13-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            cmake-deps-ubuntu-24.04-gcc-13-

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_CXX_COMPILER=g++-13 \
            -DCMAKE_C_COMPILER=gcc-13 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCHORD_BUILD_TESTS=ON \
            -DFETCHCONTENT_BASE_DIR="${{ github.workspace }}/.cmake_deps" \
            -DFETCHCONTENT_UPDATES_DISCONNECTED=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -C Release --output-on-failure --test-dir . --no-tests=error --output-junit test-results.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "build/test-results.xml"
          check_name: "Test Results (x86 GCC)"
